### ISSUE TITLE
Problem building the project

### ISSUE THREAD

**Issue by jamalromero** [skywolfmo/bookmarksai#21]
I tried to build the project following the instructions in the readme file. Probably I am missing something. But I have  issues with  the build process.
Running `npm run build` generates two files in **dist** folder: **bundle.js** and **bundle.js.LICENSE.txt**. But I think the build process should copy the necessary files for the extension to install properly 

![missing_files](https://github.com/skywolfmo/bookmarksai/assets/3081123/6033e213-4f66-4f65-b157-e4d79b780909)

Adding  **copy-webpack-plugin** to **webpack.config.js** the missing files got copied to **dist** folder

![webpack_copy](https://github.com/skywolfmo/bookmarksai/assets/3081123/b3698298-225e-4393-8272-46467468bbd0)

**Comment by skywolfmo** [comment]
thank you very much I will fix it right now

**Comment by skywolfmo** [comment]
thank you for your contribution I resolved it
